<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Provides useful structures for performing efficient concurrent operations. Original Project: https://github.com/etishor/ConcurrencyUtilities, including a port of Java's LongAdder and Striped64 classes</Description>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">$(TargetFrameworks);net461</TargetFrameworks>
    <PackageTags>concurrency;atomic</PackageTags>
  </PropertyGroup>

</Project>
